### ISSUE TITLE
Discussions group is closed?

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#18]
You invite people to discuss stuff on the Tumblr API Google group, but the group does not accept new members so it's basically impossible to ask stuff there. Is that by design?

**Comment by cyle** [comment]
Hello @sorin-costea -- no, that is not by design. We've been trying to regain access to that Google Group for a long time now. I think we'll just stop pointing people there, as you suggest. I didn't even realize it wasn't accepting new members. Sorry about that! This is the better place to ask, now.

**Comment by cyle** [comment]
We've updated the API docs to point here now, instead of the google group. Sorry again for the confusion!
