### ISSUE TITLE
OAuth Magic Link and Mobile App Webviews

### ISSUE THREAD

**Issue by ianlopshire** [tumblr/docs#35]
I apologize if this is not the correct channel for this, but I am looking for some clarification/information on implementing Tumblr OAuth authentication in mobile apps (e.g. iOS and Android). Specifically, I'm looking for details around email magic links.

For some context, the OAuth authentication page is opened in a webview inside a mobile app. The password-based authentication works as expected, but the magic link fails. The magic link is sent, but clicking the link opens it in the web browser app (e.g. Safari). This means the authentication flow never actually finishes in app.

* Is there any way to disable the magic link option when opening the authorization view?
* Is there any guidance for supporting magic links in mobile apps?

**Comment by sndsgd** [comment]
@ianlopshire Thanks for the report, and sorry for the delay. We're looking into this and will get back to you in the next few days.

**Comment by sndsgd** [comment]
We just deployed a change to fix oauth authorization for users that login using a magic link. Instead of being redirected to `/dashboard`, these users will now complete the authorization flow and be redirected to your callback url. At that point you should be able to use a deep link to redirect them to your native application.

If you are authorizing users from multiple sources (web, iOS native, etc), and you need to know _where_ to redirect the user after authorization is complete, include the `source` query parameter when you redirect the user to tumblr for [resource owner authorization](https://tools.ietf.org/html/rfc5849#section-2.2).

```
https://www.tumblr.com/oauth/authorize?oauth_token=...&source=web
```

Once the user has completed authorization, we'll include the same parameter when we redirect them to your callback url.

```
https://your.callback/url?oauth_token=...&oauth_verifier=...&source=web
```

We'll be merging some documentation changes to better reflect this shortly, but I wanted to make sure I got back to you before the end of the week. Thanks again for the report!
