### ISSUE TITLE
Random "Limit Exceeded" errors

### ISSUE THREAD

**Issue by dafi** [tumblr/docs#53]
Since yesterday 20 august I receive randomly the error "Limit Exceeded", the response is

```json
{
  "meta": {
    "status": 429,
    "msg": "Limit Exceeded"
  },
  "response": [],
  "errors": [
    {
      "title": "Limit Exceeded",
      "code": 0,
      "detail": "Errorino miserabile. Prova ancora."
    }
  ]
}


```

The headers in the response contain

    HTTP/1.1 401 Unauthorized
    Date: Sat, 21 Aug 2021 09:00:02 GMT
    X-RateLimit-Limit: 60
    X-RateLimit-Remaining: 59
    pragma: no-cache
    expires: -1
    
Obviously I don't have reached the calls count limit!

Today (21 august) everything worked fine until the error becomed permanently making unusable the clients

I used my own client and most important the [API Console](https://api.tumblr.com/console/calls/user/info)
Any call raises the error

**Comment by cyle** [comment]
Hello @dafi  -- the `401 Unauthorized` exceptions are almost always due to some kind of problem with your OAuth credentials and/or the OAuth signature. Have you tried creating a new application and seeing if the problem persists?

Unexpected `429 Limit Exceeded` responses can happen if you're making requests using an IP address that's being potentially shared with bad actors, like if you're on Amazon Web Services or other shared hosting. For this, I'd suggest opening a [Support request](https://www.tumblr.com/support), including your OAuth application name and IP address, so the Support team can help you potentially debug this further.

**Comment by dafi** [comment]
Hi @cyle you are right, the problem is related to an android library loading the avatar too often
