### ISSUE TITLE
PUT `/v2/blog/{blog-identifier}/posts` doesn't accept `state: "queued"`

### ISSUE THREAD

**Issue by AprilSylph** [tumblr/docs#58]
The documentation for [`/posts` - Create/Reblog a Post (Neue Post Format) # Request Parameters](https://github.com/tumblr/docs/blob/master/api.md#request-parameters-19) is incorrect. It states:

| Parameter | Type | Description | Default | Required? |
| --------- | ---- | ----------- | ------- | --------- |
| **state** | String | The initial [state of the new post](#note-about-post-states), such as "published" or "queued". | `"published"` | No |

But using `state: "queued"` for editing a post does not work (only `state: "queue"`).

This is more than a documentation issue. The inconsistency between the API giving `state: "queued"` but only expecting to receive `state: "queue"` seems unintended; every other variable from a post **`GET`** can be reused in a post **`PUT`** with no or insignificant transformation, and indeed every other type of post `state` is reusable (to my knowledge). So, the ideal outcome is not to update the documentation at all but to change the API's behaviour to make the documentation correct.

This problem was encountered naturally by an end user who attempted to edit a post in their queue using my WebExtension, which assumes that posts' `content`, `date`, `hide_trail`, `layout`, `placement_id`, `slug`, and (incorrectly) `state` can be reused from the API response without modification.
- AprilSylph/XKit-Rewritten#277
- AprilSylph/XKit-Rewritten#278

https://github.com/AprilSylph/XKit-Rewritten/blob/b9b22a9d909553fb15b86f34f87bf31cb7603899/src/scripts/quick_tags.js#L72-L103

**Comment by cyle** [comment]
Thanks for calling this out -- it is indeed a bit of weirdness that we haven't fixed yet, and I agree with your proposed solution. I'll see what I can do here. 👍

Behind the scenes, the NPF post state strings are a thin middleware on top of our legacy post states, so there can be odd situations like this where it's not the same string everywhere. Definitely wasn't intentional, and it wasn't caught because our own clients don't assume to be able to re-use fields between different requests in the same way (though that is a totally logical assumption to make in general about good API design).

**Comment by cyle** [comment]
We now accept `queued` as a string value for the post state on create and edit. 🎉
