### ISSUE TITLE
Asks from certain users don't appear in `/posts/submission`

### ISSUE THREAD

**Issue by nostalgebraist** [tumblr/docs#81]
I have noticed that asks sent by certain users never show up in the `/posts/submission` payload.

The issue happens rarely, is limited to particular users, and affects all asks from a user if it affects any of them.

The asks can still be fetched, edited and published through the API, if you know their post IDs beforehand.

Currently, I handle this case in my application with a manual workaround where I find the ask in the UI, open the edit window, grab the ID from the URL, and tell the application to fetch and respond to it with an internal tool.  However, this is cumbersome, and I'm also just curious what is happening here.

(I haven't checked yet whether these asks produce _notifications_ visible through the API.)

Example of a user whose asks don't show up in my submissions: [flavia-draws](https://flavia-draws.tumblr.com/)

**Comment by nightpool** [comment]
I haven't looked at the route myself, so apologies if this is entirely off base, but could this be related to the difference between asks submitted through the dashboard or mobile apps (using an NPF-native client) vs asks submitted through the legacy https://nostalgebraist-autoresponder.tumblr.com/ask iframe? (in a non-NPF form). I'm not very confident that this is related—the fact that you describe the issue as happening only very rarely makes me suspicious, since just based on priors i would expect the split between the two forms of ask submission to be more even—but it's the most obvious dichotomous "split" between asks that I can think of, would dovetail nicely with the user behavior you observe (since users probably would use either one of the two methods habitually and never think to mix them), and overall it would make sense if certain non-compatible types of asks were hidden from some clients.

More likely there's some weirdo anti-spam thing happening here though :/

**Comment by nostalgebraist** [comment]
I can see both NPF and legacy asks consistently on this endpoint.

**Comment by nightpool** [comment]
well, it was worth a shot!

**Comment by cyle** [comment]
hey @nostalgebraist sorry this is happening to you! i have a hunch why this may be happening given the details you've laid out, but some questions for you first:

> I have noticed that asks sent by certain users never show up in the /posts/submission payload. The issue happens rarely, is limited to particular users, and affects all asks from a user if it affects any of them.

if you're comfortable sharing more details, i'd suggest [filing a Support request](https://www.tumblr.com/support) with examples of which users are being filtered out, so we can look deeper at that. please reference/link to this github issue in that request to make sure it gets routed properly.

> The asks can still be fetched, edited and published through the API, if you know their post IDs beforehand.

similarly, if you can provide example post IDs in the support request where this strange behavior occurs, that'd be helpful.

lastly, do you have some dates/times of when you definitely observed this happening? that can help us narrow down anything we may have available in our logs.

**Comment by nostalgebraist** [comment]
> if you're comfortable sharing more details, i'd suggest [filing a Support request](https://www.tumblr.com/support) with examples of which users are being filtered out, so we can look deeper at that.

I've submitted a ticket.  Thanks for helping out.

For reference, below I've reproduced the part of my ticket that lists specific post IDs.

> In the last few days, I've been having this issue with asks sent by user flavia-draws.  Earlier, it's happened with other users.
> 
> Here are some recent posts whose originating asks (by flavia-draws) were affected:
> 
> https://nostalgebraist-autoresponder.tumblr.com/post/682649112064180224
> https://nostalgebraist-autoresponder.tumblr.com/post/682649864059961344
> https://nostalgebraist-autoresponder.tumblr.com/post/682650543170158592
> https://nostalgebraist-autoresponder.tumblr.com/post/682699129641713664
> https://nostalgebraist-autoresponder.tumblr.com/post/682699405195919360
> https://nostalgebraist-autoresponder.tumblr.com/post/682615315648200704
> https://nostalgebraist-autoresponder.tumblr.com/post/682613691458420736
> 
> And, here are older posts where I *think* the originating asks (by others users) were affected. I'm not totally sure because this is from searching my old logs for signs of a "manual override" I use to handle this case but also some other edge cases.
> 
> https://nostalgebraist-autoresponder.tumblr.com/post/680632505941065728
> https://nostalgebraist-autoresponder.tumblr.com/post/678848353078050816
> https://nostalgebraist-autoresponder.tumblr.com/post/676992414174658560
> https://nostalgebraist-autoresponder.tumblr.com/post/682096235935596544
> https://nostalgebraist-autoresponder.tumblr.com/post/676644528915120128

**Comment by cyle** [comment]
cool, thanks, that's super helpful. in this case, the important thing to know behind the scenes about the incoming asks / submissions endpoints is that they employ an "overfetch and filter" strategy since we don't have the state bits necessary in the database to filter the results adequately on the database level. 

this means what can happen is we try to fetch 20 incoming asks, and 15 of them are from someone who ends up getting filtered, resulting in a result size of 5, in which case we try to fetch more, and the same process can repeat, but only to a certain limit. that filtering is dependent on a number of factors that can change day-to-day or even hour-to-hour, causing seemingly weird behavior like this, especially if you're checking for asks / submissions often.

in your very specific case here, we've been able to take some action on our end that should clear it up for you and result in less filtering -- you should get a reply to your ticket soon! in the future, and if others come across this issue with their asks/submissions inbox, please feel free to [contact Support](https://www.tumblr.com/support) and we can look at what's happening and what steps we can take.
